baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"
title = "Revealing urban area from mobile positioning data"
theme = "hugo-story"

relativeURLs = "true"

[params]
  [params.seo]
    title = "Revealing urban area from mobile positioning data"
    author = "Gergő Pintér"
    description = ""
    keywords = ["mobile positioning data", "urban mobility", "privacy", "reverse-engineering"]


[services]
  [services.googleAnalytics]
    id = "G-LKEDBX9YC6"

[privacy]
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = true
