baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"
title = "Revealing urban area from mobile positioning data"
theme = "hugo-story"

[services]
  [services.googleAnalytics]
    id = "G-LKEDBX9YC6"

[privacy]
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = true
