languageCode = 'en-us'
title = 'Revealing urban area from mobile positioning data'
theme = "hugo-story"

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

[services]
  [services.googleAnalytics]
    id = "G-LKEDBX9YC6"

[privacy]
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = true
