version = 1

[[annotations]]
path = ["data/*.yml", "static/images/qr_code.png", "static/images/nagoya_blue.png", "static/images/noise_as_blur.png", "static/images/wide_v2m.png", "static/images/dallas/*", "static/images/helsinki/*", "static/images/london/*", "static/images/toronto/*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Gergő Pintér"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["static/images/Template_Matching.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Laserlicht and Benjamin Watson"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["static/images/surveillance_video_cameras.jpg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2007 Paweł Zdziarski"
SPDX-License-Identifier = "CC-BY-SA-3.0"

[[annotations]]
path = ["static/images/Airports_Network_Map.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 Martin Grandjean"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = ["themes/hugo-story/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "caressofsteel and hugo-story contributors"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = ["static/webfonts/*"]
precedence = "override"
SPDX-FileCopyrightText = "2024 Fonticons, Inc. (https://fontawesome.com)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = ["static/js/fontawesome-all.min.js", "static/css/fontawesome-all.min.css"]
precedence = "override"
SPDX-FileCopyrightText = "2024 Fonticons, Inc."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["layouts/**", "static/css/custom.css"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Gergő Pintér"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["**/.gitignore", "hugo.toml", ".github/workflows/main.yaml"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Gergő Pintér"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = ["static/css/BeerSlider.css", "static/js/BeerSlider.js"]
precedence = "override"
SPDX-FileCopyrightText = "2018 PeHaa Hetman"
SPDX-License-Identifier = "MIT"
